import { WidgetConfig } from '../types/widget';

export const dashboardWidgets: WidgetConfig[] = [
  {
    id: 'jonreygalera-vercel-app-total-visits',
    type: 'stat',
    label: 'jonreygalera.vercel.app Total Visits',
    api: 'https://api-mreyai.vercel.app/api/guest/stats',
    method: 'GET',
    headers: {
      'x-mrey-tenant': 'jonreygalera.vercel.app',
    },
    responsePath: 'count',
    size: 'sm',
    description: 'Total visits on jonreygalera.vercel.app',
    refreshInterval: 5000, 
  },
  {
    id: 'mrey-ai-vercel-app-total-visits',
    type: 'stat',
    label: 'mrey-ai.vercel.app Total Visits',
    api: 'https://api-mreyai.vercel.app/api/guest/stats',
    method: 'GET',
    headers: {
      'x-mrey-tenant': 'mrey-ai.vercel.app',
    },
    responsePath: 'count',
    size: 'sm',
    description: 'Total visits on mrey-ai.vercel.app',
    refreshInterval: 5000, 
  },
  {
    id: "baguio-city-ph-temperature",
    type: "stat",
    label: "Baguio City PH Temperature",
    api: "https://api.open-meteo.com/v1/forecast?latitude=16.4023&longitude=120.5960&current_weather=true",
    method: "GET",
    responsePath: "current_weather.temperature",
    size: "sm",
    description: "Baguio City PH Temperature",
    refreshInterval: 3600000,
    source: "Open-Meteo",
    sourceUrl: "https://open-meteo.com/",
    suffix: "°C"
  },
  {
    id: 'philippines-population',
    type: 'stat',
    label: 'Philippines Population',
    api: 'https://restcountries.com/v3.1/name/philippines',
    method: 'GET',
    responsePath: '0.population',
    size: 'sm',
    description: 'Current population of the Philippines',
    refreshInterval: 3600000, // 1 hour (doesn't change fast)
    sourceUrl: 'https://restcountries.com/v3.1/name/philippines',
  },
  {
    id: 'random-number',
    type: 'stat',
    label: 'Random Number',
    api: '/api/mock',
    method: 'POST',
    headers: {
      'Authorization': 'Bearer mreycode-signal-demo',
      'Content-Type': 'application/json',
    },
    body: {
      metric: 'random-number',
    },
    responsePath: 'payload.sessions',
    size: 'sm',
    description: 'Current random number',
    refreshInterval: 3000, 
  },
  {
    id: 'gold-futures-chart',
    type: 'line',
    label: 'Gold Futures (GC=F) - 5m',
    api: '/api/yahoo?symbol=GC=F&range=1d&interval=5m',
    method: 'GET',
    responsePath: 'series',
    xKey: 'timestamp',
    yKey: 'price',
    size: 'lg',
    description: 'Today\'s 5-minute interval price action for Gold',
    prefix: '$',
    refreshInterval: 300000, // 5 minutes matching candle interval
    source: 'finance.yahoo.com',
    sourceUrl: 'https://finance.yahoo.com/quote/GC=F',
  },
  {
    id: 'covid-total-cases',
    type: 'stat',
    label: 'COVID-19 Total Cases',
    api: 'https://disease.sh/v3/covid-19/all',
    method: 'GET',
    responsePath: 'cases',
    size: 'sm',
    description: 'Total confirmed COVID-19 cases worldwide',
    refreshInterval: 3600000,
    abbreviate: true,
    source: 'disease.sh',
    sourceUrl: 'https://disease.sh/v3/covid-19/all',
  },
  {
    id: 'covid-total-deaths',
    type: 'stat',
    label: 'COVID-19 Total Deaths',
    api: 'https://disease.sh/v3/covid-19/all',
    method: 'GET',
    responsePath: 'deaths',
    size: 'sm',
    description: 'Total confirmed COVID-19 deaths worldwide',
    refreshInterval: 3600000,
    abbreviate: true,
    color: 'down',
    source: 'disease.sh',
    sourceUrl: 'https://disease.sh/v3/covid-19/all',
  },
  {
    id: 'covid-total-recovered',
    type: 'stat',
    label: 'COVID-19 Total Recovered',
    api: 'https://disease.sh/v3/covid-19/all',
    method: 'GET',
    responsePath: 'recovered',
    size: 'sm',
    description: 'Total confirmed COVID-19 recoveries worldwide',
    refreshInterval: 3600000,
    abbreviate: true,
    source: 'disease.sh',
    sourceUrl: 'https://disease.sh/v3/covid-19/all',
  },
  {
    id: 'covid-active-cases',
    type: 'stat',
    label: 'COVID-19 Active Cases',
    api: 'https://disease.sh/v3/covid-19/all',
    method: 'GET',
    responsePath: 'active',
    size: 'sm',
    description: 'Total active COVID-19 cases worldwide',
    refreshInterval: 3600000,
    abbreviate: true,
    source: 'disease.sh',
    sourceUrl: 'https://disease.sh/v3/covid-19/all',
  },
  {
    id: 'covid-critical-cases',
    type: 'stat',
    label: 'COVID-14 Critical Cases',
    api: 'https://disease.sh/v3/covid-19/all',
    method: 'GET',
    responsePath: 'critical',
    size: 'sm',
    description: 'Total critical COVID-19 cases worldwide',
    refreshInterval: 3600000,
    abbreviate: true,
    source: 'disease.sh',
    sourceUrl: 'https://disease.sh/v3/covid-19/all',
  },
  {
    id: 'covid-today-cases',
    type: 'stat',
    label: 'COVID-19 Cases Today',
    api: 'https://disease.sh/v3/covid-19/all',
    method: 'GET',
    responsePath: 'todayCases',
    size: 'sm',
    description: 'Confirmed COVID-19 cases reported today',
    refreshInterval: 3600000,
    source: 'disease.sh',
    sourceUrl: 'https://disease.sh/v3/covid-19/all',
  },
  {
    id: 'covid-today-deaths',
    type: 'stat',
    label: 'COVID-19 Deaths Today',
    api: 'https://disease.sh/v3/covid-19/all',
    method: 'GET',
    responsePath: 'todayDeaths',
    size: 'sm',
    description: 'Confirmed COVID-19 deaths reported today',
    refreshInterval: 3600000,
    source: 'disease.sh',
    sourceUrl: 'https://disease.sh/v3/covid-19/all',
  },
  {
    id: 'global-population-covid',
    type: 'stat',
    label: 'Global Population',
    api: 'https://disease.sh/v3/covid-19/all',
    method: 'GET',
    responsePath: 'population',
    size: 'sm',
    description: 'Total global population (statistical data)',
    refreshInterval: 86400000,
    abbreviate: true,
    source: 'disease.sh',
    sourceUrl: 'https://disease.sh/v3/covid-19/all',
  },
  {
    id: 'covid-affected-countries',
    type: 'stat',
    label: 'Affected Countries',
    api: 'https://disease.sh/v3/covid-19/all',
    method: 'GET',
    responsePath: 'affectedCountries',
    size: 'sm',
    description: 'Total number of countries/territories affected',
    refreshInterval: 3600000,
    source: 'disease.sh',
    sourceUrl: 'https://disease.sh/v3/covid-19/all',
  },
  {
    id: 'traffic-sources-bar',
    type: 'bar',
    label: 'Traffic Sources - MOCK',
    api: '/api/mock',
    method: 'POST',
    body: {
      metric: 'traffic-sources',
    },
    responsePath: 'stats.trafficData',
    xKey: 'source',
    yKey: 'visits',
    size: 'md',
    description: 'Distribution of traffic sources',
    refreshInterval: 10000,
  },
  {
    id: 'revenue-trends-area',
    type: 'area',
    label: 'Revenue Trends - MOCK',
    api: '/api/mock?type=chart-revenue',
    method: 'GET',
    responsePath: 'result.series',
    xKey: 'day',
    yKey: 'revenue',
    size: 'lg',
    description: 'Weekly revenue growth visualization',
    refreshInterval: 60000,
    prefix: '$',
  },
];
