import { WidgetConfig } from '@/types/widget';

export interface WidgetTemplate {
  label: string;
  config: Omit<WidgetConfig, 'id'> & { id: string };
}

export const TEMPLATES: WidgetTemplate[] = [
  // ── Stats ──────────────────────────────────────────────────────────
  {
    label: 'Stat: Philippines Population',
    config: {
      id: 'tpl-ph-population',
      type: 'stat',
      label: 'Philippines Population',
      api: 'https://restcountries.com/v3.1/name/philippines',
      method: 'GET',
      responsePath: '0.population',
      size: 'sm',
      description: 'Current population of the Philippines',
      refreshInterval: 86400000,
      abbreviate: true,
      source: 'restcountries.com',
      sourceUrl: 'https://restcountries.com/v3.1/name/philippines',
    },
  },
  {
    label: 'Stat: Gold Futures Price',
    config: {
      id: 'tpl-gold-price',
      type: 'stat',
      label: 'Gold Futures (GC=F)',
      api: '/api/yahoo?symbol=GC=F&range=1d&interval=1d',
      method: 'GET',
      responsePath: 'series.0.price',
      size: 'sm',
      description: "Today's Gold Futures price",
      prefix: '$',
      refreshInterval: 300000,
      source: 'finance.yahoo.com',
      sourceUrl: 'https://finance.yahoo.com/quote/GC=F',
      color: 'up',
    },
  },
  {
    label: 'Stat: Color Rules (Threshold)',
    config: {
      id: 'tpl-color-rules',
      type: 'stat',
      label: 'Error Rate',
      api: '/api/mock',
      method: 'POST',
      body: { metric: 'random-number' },
      responsePath: 'payload.sessions',
      size: 'sm',
      suffix: '%',
      description: 'Value-based dynamic color threshold example',
      refreshInterval: 5000,
      colorRules: {
        rules: [
          { condition: 'below', value: 30, color: 'up' },
          { condition: 'above', value: 70, color: 'down' },
        ],
      },
    },
  },
  // ── COVID-19 (disease.sh) ───────────────────────────────────────────
  {
    label: 'COVID: Total Cases',
    config: {
      id: 'tpl-covid-total-cases',
      type: 'stat',
      label: 'COVID-19 Total Cases',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'cases',
      size: 'sm',
      description: 'Total confirmed COVID-19 cases worldwide',
      refreshInterval: 3600000,
      abbreviate: true,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
      color: 'warning',
    },
  },
  {
    label: 'COVID: Total Deaths',
    config: {
      id: 'tpl-covid-total-deaths',
      type: 'stat',
      label: 'COVID-19 Total Deaths',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'deaths',
      size: 'sm',
      description: 'Total confirmed COVID-19 deaths worldwide',
      refreshInterval: 3600000,
      abbreviate: true,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
      color: 'down',
    },
  },
  {
    label: 'COVID: Total Recovered',
    config: {
      id: 'tpl-covid-total-recovered',
      type: 'stat',
      label: 'COVID-19 Total Recovered',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'recovered',
      size: 'sm',
      description: 'Total confirmed COVID-19 recoveries worldwide',
      refreshInterval: 3600000,
      abbreviate: true,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
      color: 'info',
    },
  },
  {
    label: 'COVID: Active Cases',
    config: {
      id: 'tpl-covid-active',
      type: 'stat',
      label: 'COVID-19 Active Cases',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'active',
      size: 'sm',
      description: 'Active COVID-19 cases worldwide',
      refreshInterval: 3600000,
      abbreviate: true,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
      color: 'warning',
    },
  },
  {
    label: 'COVID: Critical Cases',
    config: {
      id: 'tpl-covid-critical',
      type: 'stat',
      label: 'COVID-19 Critical Cases',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'critical',
      size: 'sm',
      description: 'Total critical COVID-19 cases worldwide',
      refreshInterval: 3600000,
      abbreviate: true,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
      color: 'down',
    },
  },
  {
    label: 'COVID: Cases Today',
    config: {
      id: 'tpl-covid-today-cases',
      type: 'stat',
      label: 'COVID-19 Cases Today',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'todayCases',
      size: 'sm',
      description: 'New confirmed COVID-19 cases reported today',
      refreshInterval: 3600000,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
    },
  },
  {
    label: 'COVID: Deaths Today',
    config: {
      id: 'tpl-covid-today-deaths',
      type: 'stat',
      label: 'COVID-19 Deaths Today',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'todayDeaths',
      size: 'sm',
      description: 'New COVID-19 deaths reported today',
      refreshInterval: 3600000,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
      color: 'down',
    },
  },
  {
    label: 'COVID: Global Population',
    config: {
      id: 'tpl-covid-global-population',
      type: 'stat',
      label: 'Global Population',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'population',
      size: 'sm',
      description: 'Total global population (disease.sh statistical data)',
      refreshInterval: 86400000,
      abbreviate: true,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
    },
  },
  {
    label: 'COVID: Affected Countries',
    config: {
      id: 'tpl-covid-affected-countries',
      type: 'stat',
      label: 'Affected Countries',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'affectedCountries',
      size: 'sm',
      description: 'Total countries/territories affected by COVID-19',
      refreshInterval: 3600000,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
    },
  },
  // ── Charts ─────────────────────────────────────────────────────────
  {
    label: 'Chart: Gold Futures Line (5m)',
    config: {
      id: 'tpl-gold-line',
      type: 'line',
      label: 'Gold Futures (GC=F) — 5m',
      api: '/api/yahoo?symbol=GC=F&range=1d&interval=5m',
      method: 'GET',
      responsePath: 'series',
      xKey: 'timestamp',
      yKey: 'price',
      size: 'lg',
      prefix: '$',
      description: "Today's 5-minute Gold price action",
      refreshInterval: 300000,
      source: 'finance.yahoo.com',
      sourceUrl: 'https://finance.yahoo.com/quote/GC=F',
    },
  },
  {
    label: 'Chart: Gold Futures Bar (5m)',
    config: {
      id: 'tpl-gold-bar',
      type: 'bar',
      label: 'Gold Futures (GC=F) — 5m',
      api: '/api/yahoo?symbol=GC=F&range=1d&interval=5m',
      method: 'GET',
      responsePath: 'series',
      xKey: 'timestamp',
      yKey: 'price',
      size: 'lg',
      prefix: '$',
      description: "Today's 5-minute Gold price action",
      refreshInterval: 300000,
      source: 'finance.yahoo.com',
      sourceUrl: 'https://finance.yahoo.com/quote/GC=F',
    },
  },
  {
    label: 'Chart: Gold Futures Area (5m)',
    config: {
      id: 'tpl-gold-area',
      type: 'area',
      label: 'Gold Futures (GC=F) — 5m',
      api: '/api/yahoo?symbol=GC=F&range=1d&interval=5m',
      method: 'GET',
      responsePath: 'series',
      xKey: 'timestamp',
      yKey: 'price',
      size: 'lg',
      prefix: '$',
      description: "Today's 5-minute Gold price action",
      refreshInterval: 300000,
      source: 'finance.yahoo.com',
      sourceUrl: 'https://finance.yahoo.com/quote/GC=F',
    },
  },
];
