import { WidgetConfig } from '@/types/widget';

export interface WidgetTemplate {
  label: string;
  config: Omit<WidgetConfig, 'id'> & { id: string };
}

export const TEMPLATES: WidgetTemplate[] = [
  // ── GitHub ──────────────────────────────────────────────────────────
  {
    label: 'GitHub: Public Repositories (Stat)',
    config: {
      id: 'jonreygalera-github-repos',
      type: 'stat',
      label: 'Jon Rey | GitHub Public Repos',
      api: 'https://api.github.com/users/jonreygalera',
      method: 'GET',
      responsePath: 'public_repos',
      size: 'sm',
      description: 'Number of public repositories on GitHub',
      refreshInterval: 3600000,
      source: 'GitHub',
      sourceUrl: 'https://github.com/jonreygalera?tab=repositories',
      color: 'info',
      config: {},
    },
  },
  {
    label: 'GitHub: Followers (Stat)',
    config: {
      id: 'jonreygalera-github-followers',
      type: 'stat',
      label: 'Jon Rey | GitHub Followers',
      api: 'https://api.github.com/users/jonreygalera',
      method: 'GET',
      responsePath: 'followers',
      size: 'sm',
      description: 'Number of followers on GitHub',
      refreshInterval: 3600000,
      source: 'GitHub',
      sourceUrl: 'https://github.com/jonreygalera?tab=followers',
      color: 'up',
      config: {},
    },
  },
  {
    label: 'GitHub: Following (Stat)',
    config: {
      id: 'jonreygalera-github-following',
      type: 'stat',
      label: 'Jon Rey | GitHub Following',
      api: 'https://api.github.com/users/jonreygalera',
      method: 'GET',
      responsePath: 'following',
      size: 'sm',
      description: 'Number of users followed on GitHub',
      refreshInterval: 3600000,
      source: 'GitHub',
      sourceUrl: 'https://github.com/jonreygalera?tab=following',
      color: 'muted',
      config: {},
    },
  },
  {
    label: 'GitHub: Repositories (List)',
    config: {
      id: 'tpl-list-github',
      type: 'list',
      label: 'My Repositories',
      api: 'https://api.github.com/users/jonreygalera/repos?sort=updated&per_page=5',
      method: 'GET',
      responsePath: '',
      transformer: '(val) => val.map(r => ({ name: r.name, value: r.stargazers_count + " ★" }))',
      size: 'md',
      description: 'List of recent GitHub repositories',
      source: 'api.github.com',
      config: {},
    },
  },
  // ── Stats ──────────────────────────────────────────────────────────
  {
    label: 'Stat: Philippines Population',
    config: {
      id: 'tpl-ph-population',
      type: 'stat',
      label: 'Philippines Population',
      api: 'https://restcountries.com/v3.1/name/philippines',
      method: 'GET',
      responsePath: '0.population',
      size: 'sm',
      description: 'Current population of the Philippines',
      refreshInterval: 86400000,
      source: 'restcountries.com',
      sourceUrl: 'https://restcountries.com/v3.1/name/philippines',
      config: {
        abbreviate: true,
      },
    },
  },
  {
    label: 'Stat: Gold Futures Price',
    config: {
      id: 'tpl-gold-price',
      type: 'stat',
      label: 'Gold Futures (GC=F)',
      api: '/api/yahoo?symbol=GC=F&range=1d&interval=1d',
      method: 'GET',
      responsePath: 'series.0.price',
      size: 'sm',
      description: "Today's Gold Futures price",
      refreshInterval: 300000,
      source: 'finance.yahoo.com',
      sourceUrl: 'https://finance.yahoo.com/quote/GC=F',
      color: 'up',
      config: {
        prefix: '$',
      },
    },
  },
  {
    label: 'Stat: Color Rules (Threshold)',
    config: {
      id: 'tpl-color-rules',
      type: 'stat',
      label: 'Error Rate',
      api: '/api/mock',
      method: 'POST',
      body: { metric: 'random-number' },
      responsePath: 'payload.sessions',
      size: 'sm',
      description: 'Value-based dynamic color threshold example',
      refreshInterval: 5000,
      colorRules: {
        rules: [
          { condition: 'below', value: 30, color: 'up' },
          { condition: 'above', value: 70, color: 'down' },
        ],
      },
      config: {
        suffix: '%',
      },
    },
  },
  // ── COVID-19 (disease.sh) ───────────────────────────────────────────
  {
    label: 'COVID: Total Cases',
    config: {
      id: 'tpl-covid-total-cases',
      type: 'stat',
      label: 'COVID-19 Total Cases',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'cases',
      size: 'sm',
      description: 'Total confirmed COVID-19 cases worldwide',
      refreshInterval: 3600000,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
      color: 'warning',
      config: {
        abbreviate: true,
      },
    },
  },
    {
    label: 'COVID: Total Deaths',
    config: {
      id: 'tpl-covid-total-deaths',
      type: 'stat',
      label: 'COVID-19 Total Deaths',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'deaths',
      size: 'sm',
      description: 'Total confirmed COVID-19 deaths worldwide',
      refreshInterval: 3600000,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
      color: 'down',
      config: {
        abbreviate: true,
      },
    },
  },
  {
    label: 'COVID: Total Recovered',
    config: {
      id: 'tpl-covid-total-recovered',
      type: 'stat',
      label: 'COVID-19 Total Recovered',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'recovered',
      size: 'sm',
      description: 'Total confirmed COVID-19 recoveries worldwide',
      refreshInterval: 3600000,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
      color: 'info',
      config: {
        abbreviate: true,
      },
    },
  },
  {
    label: 'COVID: Active Cases',
    config: {
      id: 'tpl-covid-active',
      type: 'stat',
      label: 'COVID-19 Active Cases',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'active',
      size: 'sm',
      description: 'Active COVID-19 cases worldwide',
      refreshInterval: 3600000,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
      color: 'warning',
      config: {
        abbreviate: true,
      },
    },
  },
  {
    label: 'COVID: Critical Cases',
    config: {
      id: 'tpl-covid-critical',
      type: 'stat',
      label: 'COVID-19 Critical Cases',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'critical',
      size: 'sm',
      description: 'Total critical COVID-19 cases worldwide',
      refreshInterval: 3600000,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
      color: 'down',
      config: {
        abbreviate: true,
      },
    },
  },
  {
    label: 'COVID: Cases Today',
    config: {
      id: 'tpl-covid-today-cases',
      type: 'stat',
      label: 'COVID-19 Cases Today',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'todayCases',
      size: 'sm',
      description: 'New confirmed COVID-19 cases reported today',
      refreshInterval: 3600000,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
    },
  },
  {
    label: 'COVID: Deaths Today',
    config: {
      id: 'tpl-covid-today-deaths',
      type: 'stat',
      label: 'COVID-19 Deaths Today',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'todayDeaths',
      size: 'sm',
      description: 'New COVID-19 deaths reported today',
      refreshInterval: 3600000,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
      color: 'down',
    },
  },
  {
    label: 'COVID: Global Population',
    config: {
      id: 'tpl-covid-global-population',
      type: 'stat',
      label: 'Global Population',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'population',
      size: 'sm',
      description: 'Total global population (disease.sh statistical data)',
      refreshInterval: 86400000,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
      config: {
        abbreviate: true,
      },
    },
  },
  {
    label: 'COVID: Affected Countries',
    config: {
      id: 'tpl-covid-affected-countries',
      type: 'stat',
      label: 'Affected Countries',
      api: 'https://disease.sh/v3/covid-19/all',
      method: 'GET',
      responsePath: 'affectedCountries',
      size: 'sm',
      description: 'Total countries/territories affected by COVID-19',
      refreshInterval: 3600000,
      source: 'disease.sh',
      sourceUrl: 'https://disease.sh/v3/covid-19/all',
    },
  },
  // ── Charts ─────────────────────────────────────────────────────────
  {
    label: 'Chart: Gold Futures Line (5m)',
    config: {
      id: 'tpl-gold-line',
      type: 'chart',
      label: 'Gold Futures (GC=F) — 5m',
      api: '/api/yahoo?symbol=GC=F&range=1d&interval=5m',
      method: 'GET',
      responsePath: 'series',
      size: 'lg',
      description: "Today's 5-minute Gold price action",
      refreshInterval: 300000,
      source: 'finance.yahoo.com',
      sourceUrl: 'https://finance.yahoo.com/quote/GC=F',
      config: {
        chart: 'line',
        xKey: 'timestamp',
        yKey: 'price',
        prefix: '$',
      },
    },
  },
  {
    label: 'Chart: Gold Futures Bar (5m)',
    config: {
      id: 'tpl-gold-bar',
      type: 'chart',
      label: 'Gold Futures (GC=F) — 5m',
      api: '/api/yahoo?symbol=GC=F&range=1d&interval=5m',
      method: 'GET',
      responsePath: 'series',
      size: 'lg',
      description: "Today's 5-minute Gold price action",
      refreshInterval: 300000,
      source: 'finance.yahoo.com',
      sourceUrl: 'https://finance.yahoo.com/quote/GC=F',
      config: {
        chart: 'bar',
        xKey: 'timestamp',
        yKey: 'price',
        prefix: '$',
      },
    },
  },
  {
    label: 'Chart: Gold Futures Area (5m)',
    config: {
      id: 'tpl-gold-area',
      type: 'chart',
      label: 'Gold Futures (GC=F) — 5m',
      api: '/api/yahoo?symbol=GC=F&range=1d&interval=5m',
      method: 'GET',
      responsePath: 'series',
      size: 'lg',
      description: "Today's 5-minute Gold price action",
      refreshInterval: 300000,
      source: 'finance.yahoo.com',
      sourceUrl: 'https://finance.yahoo.com/quote/GC=F',
      config: {
        chart: 'area',
        xKey: 'timestamp',
        yKey: 'price',
        prefix: '$',
      },
    },
  },
  // ── Interactive & Specialized ──────────────────────────────────────
  {
    label: 'Iframe: External Dashboard',
    config: {
      id: 'tpl-iframe-ext',
      type: 'iframe',
      label: '🐱💻 When Your Cat Takes Over Your PC! 😹💤',
      responsePath: '',
      size: 'lg',
      description: 'Embed an external dashboard via Iframe',
      accentColor: '#0070f3',
      config: {
        iframeUrl: 'https://www.youtube.com/embed/dn5OzbHrkp4',
      },
    },
  },
  {
    label: 'Clock: Analog & Digital',
    config: {
      id: 'tpl-clock-custom',
      type: 'clock',
      label: 'World Clock',
      api: 'none',
      responsePath: '',
      size: 'sm',
      description: 'Professional bento clock widget',
      accentColor: '#fbbf24',
      config: {
        displayType: 'analog',
        timezone: 'Asia/Manila',
      },
    },
  },
  {
    label: 'Progress: System Capacity',
    config: {
      id: 'tpl-progress-mock',
      type: 'progress',
      label: 'Server Storage',
      api: '/api/mock',
      method: 'POST',
      body: { metric: 'random-number' },
      responsePath: 'payload.sessions',
      size: 'sm',
      description: 'Visual progress bar for metrics',
      accentColor: '#3b82f6',
      config: {},
    },
  },
  {
    label: 'Status: System Online',
    config: {
      id: 'tpl-status-check',
      type: 'status',
      label: 'API Gateway',
      api: 'https://api.github.com/zen',
      responsePath: '',
      transformer: '(val) => !!val', // Returns true if response exists
      size: 'sm',
      description: 'System availability indicator',
      config: {},
    },
  },
  // ── Predefined Project Metrics ─────────────────────────────────────
  {
    label: 'Metrics: Signal Vercel Visits',
    config: {
      id: 'mreycode-signal-vercel-app-total-visits',
      type: 'stat',
      label: 'mreycode-signal.vercel.app Total Visits',
      api: 'https://api-mreyai.vercel.app/api/guest/stats',
      method: 'GET',
      headers: { 'x-mrey-tenant': 'mreycode-signal.vercel.app' },
      responsePath: 'count',
      size: 'sm',
      description: 'Total visits on mreycode-signal.vercel.app',
      refreshInterval: 3600000,
      color: 'up',
      config: {},
      sourceUrl: 'https://api-mreyai.vercel.app',
    },
  },
  {
    label: 'Metrics: Mrey AI Vercel Visits',
    config: {
      id: 'mrey-ai-vercel-app-total-visits',
      type: 'stat',
      label: 'mrey-ai.vercel.app Total Visits',
      api: 'https://api-mreyai.vercel.app/api/guest/stats',
      method: 'GET',
      headers: { 'x-mrey-tenant': 'mrey-ai.vercel.app' },
      responsePath: 'count',
      size: 'sm',
      description: 'Total visits on mrey-ai.vercel.app',
      refreshInterval: 3600000,
      color: 'up',
      config: {},
      sourceUrl: 'https://api-mreyai.vercel.app',
    },
  },
  {
    label: 'Metrics: Jon Rey Vercel Visits',
    config: {
      id: 'jonreygalera-vercel-app-total-visits',
      type: 'stat',
      label: 'jonreygalera.vercel.app Total Visits',
      api: 'https://api-mreyai.vercel.app/api/guest/stats',
      method: 'GET',
      headers: { 'x-mrey-tenant': 'jonreygalera.vercel.app' },
      responsePath: 'count',
      size: 'sm',
      description: 'Total visits on jonreygalera.vercel.app',
      refreshInterval: 3600000,
      color: 'up',
      config: {},
      sourceUrl: 'https://api-mreyai.vercel.app',
    },
  },
  {
    label: 'Weather: Baguio City Temperature',
    config: {
      id: "baguio-city-ph-temperature",
      type: "stat",
      label: "Baguio City PH Temperature",
      api: "https://api.open-meteo.com/v1/forecast?latitude=16.4023&longitude=120.5960&current_weather=true",
      method: "GET",
      responsePath: "current_weather.temperature",
      size: "sm",
      description: "Baguio City PH Temperature",
      refreshInterval: 3600000,
      sourceUrl: "https://api.open-meteo.com/v1/forecast?latitude=16.4023&longitude=120.5960&current_weather=true",
      colorRules: {
        rules: [
          { condition: 'below', value: 18, color: 'up' },   // Nice & Cold (Green)
          { condition: 'above', value: 25, color: 'down' }, // Too Hot (Red)
        ]
      },
      config: { suffix: "°C" },
      signals: [
        {
          id: 'cold-alert',
          label: 'It\'s Cold in Baguio!',
          condition: 'below',
          threshold: 15,
          action: ['pulse', 'notify', 'sound', 'notify-in-app'],
          duration: 10,
          enabled: true
        }
      ]
    },
  },
  {
    label: 'Stat: BTC-USD Price',
    config: {
      id: "tpl-btc-price",
      type: "stat",
      label: "BTC-USD",
      api: "/api/yahoo?symbol=BTC-USD&range=1d&interval=1d",
      method: "GET",
      responsePath: "series.0.price",
      size: "sm",
      description: "Today's BTC-USD price",
      refreshInterval: 300000,
      source: "finance.yahoo.com",
      sourceUrl: "https://finance.yahoo.com/quote/BTC-USD",
      color: "up",
      config: { prefix: "$" },
    },
  },
  {
    label: 'Demographics: PH Population',
    config: {
      id: 'philippines-population',
      type: 'stat',
      label: 'Philippines Population',
      api: 'https://restcountries.com/v3.1/name/philippines',
      method: 'GET',
      responsePath: '0.population',
      size: 'sm',
      description: 'Current population of the Philippines',
      refreshInterval: 3600000,
      sourceUrl: 'https://restcountries.com/v3.1/name/philippines',
      config: { abbreviate: true },
    },
  },
  {
    label: 'Chart: Traffic Sources (Demo)',
    config: {
      id: 'traffic-sources-bar',
      type: 'chart',
      label: 'Traffic Sources',
      api: '/api/mock',
      method: 'POST',
      body: { metric: 'traffic-sources' },
      responsePath: 'stats.trafficData',
      size: 'md',
      description: 'Distribution of traffic sources',
      refreshInterval: 10000,
      config: { chart: 'bar', xKey: 'source', yKey: 'visits' },
    },
  },
  {
    label: 'Chart: Revenue Trends (Demo)',
    config: {
      id: 'revenue-trends-area',
      type: 'chart',
      label: 'Revenue Trends',
      api: '/api/mock?type=chart-revenue',
      method: 'GET',
      responsePath: 'result.series',
      size: 'lg',
      description: 'Weekly revenue growth visualization',
      refreshInterval: 60000,
      config: { chart: 'area', xKey: 'day', yKey: 'revenue', prefix: '$' },
    },
  },
  // ── Labels & Headers ────────────────────────────────────────────────
  {
    label: 'Label: Section Header (Hero)',
    config: {
      id: 'tpl-label-header',
      type: 'label',
      label: 'Main Dashboard',
      size: 'md',
      description: 'Bold section title for organization',
      config: {
        variant: 'hero',
        align: 'left',
        subtitle: 'Real-time system overview and metrics',
      },
    },
  },
  {
    label: 'Label: Navigation Link (Pill)',
    config: {
      id: 'tpl-label-link',
      type: 'label',
      label: 'Documentation',
      size: 'sm',
      description: 'Interactive shortcut to external resources',
      config: {
        variant: 'pill',
        icon: 'ExternalLink',
        align: 'center',
        link: 'https://github.com/jonreygalera/mreycode-signal',
      },
    },
  },
  {
    label: 'Label: Metric Label (Simple)',
    config: {
      id: 'tpl-label-simple',
      type: 'label',
      label: 'API Status',
      size: 'sm',
      description: 'Simple text label with an icon',
      config: {
        variant: 'simple',
        icon: 'Activity',
        align: 'left',
        subtitle: 'Operational',
      },
    },
  },
  {
    label: 'Network: Public IP Address',
    config: {
      id: 'tpl-label-ip',
      type: 'label',
      label: 'Public IP',
      api: 'https://ipapi.co/json',
      method: 'GET',
      responsePath: 'ip',
      size: 'sm',
      description: 'Your current public IP address',
      refreshInterval: 3600000,
      config: {
        variant: 'pill',
        icon: 'Globe',
        align: 'center',
      },
    },
  },
  {
    label: 'Network: Connection Location',
    config: {
      id: 'tpl-label-location',
      type: 'label',
      label: 'Connection Location',
      api: 'https://ipapi.co/json',
      method: 'GET',
      responsePath: '',
      transformer: '(val) => `${val.city}, ${val.country_name}`',
      size: 'sm',
      description: 'Geographic location of your IP',
      refreshInterval: 3600000,
      config: {
        variant: 'simple',
        icon: 'MapPin',
        align: 'left',
        subtitle: 'Detected Region',
      },
    },
  },
];
